services:
  - type: web
    name: standoff2-shop-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: HEARTBEAT_CHANNEL_ID
        sync: false
      - key: HEARTBEAT_INTERVAL_MINUTES
        value: "10"
      - key: SUPPORT_USERNAME
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.9"
